const root=document.getElementById("admin-content"),title=document.getElementById("page-title");
async function api(url,options={}){const r=await fetch(url,{credentials:"include",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}
function toast(m,t="success"){const r=document.getElementById("toast-root"),x=document.createElement("div");x.className=`toast ${t}`;x.textContent=m;r.appendChild(x);setTimeout(()=>x.remove(),3000)}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const labels={placements:"Placements",companyCalls:"Company Calls",jobs:"Job Notifications",training:"Training",courses:"Courses",interviews:"Interviews",tests:"Tests",achievements:"Achievements",hiring:"Hiring Status"};
function overview(){title.textContent="Overview";root.innerHTML='<div class="loader"></div>';api("/api/admin/stats").then(s=>{root.innerHTML=`<div class="dash-hero"><div><div class="eyebrow">CAMPUS MANAGEMENT PROTOCOL</div><h2>Admin command center</h2><p class="muted">Manage live student career data stored in MongoDB.</p></div><button class="btn primary" onclick="seedHint()">Seed Data Guide</button></div><div class="dashboard-grid">${Object.entries({students:"Students",placements:"Placements",companies:"Company Calls",jobs:"Jobs",training:"Training",courses:"Courses",interviews:"Interviews",tests:"Tests",hired:"Selected / Offers"}).map(([k,v])=>`<div class="dashboard-card"><h3>${v}</h3><div class="big">${s[k]??0}</div><small class="muted">Live database count</small></div>`).join("")}</div>`}).catch(e=>{toast(e.message,"error");if(e.message.includes("Admin"))location.href="/dashboard.html"})}
function seedHint(){toast("Sample data is included. Run npm run seed to populate MongoDB.")}
async function students(){title.textContent="Students";root.innerHTML='<div class="loader"></div>';const {data}=await api("/api/admin/students");root.innerHTML=`<div class="dashboard-card full-card"><div class="page-toolbar"><input id="student-search" placeholder="Search student..."><button class="btn ghost" onclick="filterStudents()">Search</button></div><div class="item-list" id="student-list">${data.map(u=>`<div class="list-item student-row"><b>${esc(u.name)}</b><small>${esc(u.email)} • ${esc(u.profile?.department||"—")} • ${esc(u.profile?.course||"—")} • CGPA ${esc(u.profile?.cgpa||"—")}</small><small>Profile completion: ${esc(u.profile?.profileCompletion||0)}% • ID: ${esc(u.studentId||u.profile?.rollNumber||"—")}</small></div>`).join("")}</div></div>`;window._students=data}
function filterStudents(){const q=(document.getElementById("student-search").value||"").toLowerCase();document.querySelectorAll(".student-row").forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?"block":"none")}
async function resource(resource){title.textContent=labels[resource]||resource;root.innerHTML='<div class="loader"></div>';const {data}=await api(`/api/admin/${resource}`);let rows=data.map(x=>`<div class="list-item"><b>${esc(x.companyName||x.title||x.name||x.company||"Record")}</b><small>${esc(x.jobRole||x.role||x.provider||x.category||x.description||"")}</small><div class="admin-actions"><button class="btn ghost" onclick='editRecord(${JSON.stringify(resource)},${JSON.stringify(x)})'>Edit</button><button class="btn ghost danger" onclick="deleteRecord('${resource}','${x._id}')">Delete</button></div></div>`).join("");if(resource==="hiring")rows=data.map(x=>`<div class="list-item"><b>${esc(x.userId?.name||"Student")} — ${esc(x.company)} / ${esc(x.role)}</b><small>${esc(x.applicationStatus)} • ${esc(x.interviewStatus)} • ${esc(x.offerStatus)}</small><div class="admin-actions"><button class="btn ghost" onclick='editRecord("hiring",${JSON.stringify(x)})'>Update</button></div></div>`).join("");root.innerHTML=`<div class="page-toolbar"><button class="btn primary" onclick="newRecord('${resource}')">+ Add ${labels[resource]||resource}</button><button class="btn ghost" onclick="resource('${resource}')">Refresh</button></div><div class="dashboard-card full-card">${rows||'<div class="empty">No records.</div>'}</div>`}
function newRecord(resource){const defaults={placements:{companyName:"",jobRole:"",package:"₹6 LPA",location:"Hyderabad",eligibility:"60%+",requiredSkills:["Java","DSA"],applicationDeadline:new Date(Date.now()+14*86400000).toISOString(),jobType:"Full Time",status:"Open"},companyCalls:{companyName:"",role:"",eligibility:"60%+",date:new Date(Date.now()+7*86400000).toISOString(),venue:"Placement Cell",requiredSkills:[]},jobs:{title:"",company:"",type:"Full Time",location:"Hyderabad",salary:"₹6 LPA",deadline:new Date(Date.now()+14*86400000).toISOString(),description:"",link:"#",newNotification:true},training:{title:"",provider:"",duration:"6 Weeks",skills:[],startDate:new Date(Date.now()+7*86400000).toISOString(),category:"Technical Training",registrationLink:"#"},courses:{title:"",provider:"",category:"Full Stack",duration:"8 Weeks",level:"Beginner",skills:[],link:"#"},interviews:{company:"",role:"",interviewDate:new Date(Date.now()+7*86400000).toISOString(),interviewType:"Technical + HR",status:"Scheduled",preparation:[]},tests:{title:"",category:"Aptitude",duration:10,difficulty:"Basic",questions:[{question:"Sample question?",options:["A","B","C","D"],answer:0,marks:1}]},achievements:{title:"",description:"",date:new Date().toISOString(),category:"Achievement",certificate:""}};editRecord(resource,defaults[resource]||{})}
function editRecord(resource,item){if(resource==="hiring"){const userId=item.userId?._id||item.userId||prompt("Enter student User ID");if(!userId)return;const body={userId,company:prompt("Company",item.company||"")||item.company,role:prompt("Role",item.role||"")||item.role,applicationStatus:prompt("Status: Applied / Shortlisted / Interview Scheduled / Selected / Rejected / Offer Received",item.applicationStatus||"Applied")||"Applied",interviewStatus:prompt("Interview status",item.interviewStatus||"Not Scheduled")||"Not Scheduled",offerStatus:prompt("Offer status",item.offerStatus||"Pending")||"Pending",notes:prompt("Notes",item.notes||"")||""};api("/api/admin/hiring",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(d=>{toast(d.message);resourceViewAfter("hiring")}).catch(e=>toast(e.message,"error"));return}const raw=prompt(`Edit ${labels[resource]} as JSON`,JSON.stringify(item,null,2));if(!raw)return;let body;try{body=JSON.parse(raw);delete body._id;delete body.__v;delete body.createdAt;delete body.updatedAt}catch{toast("Invalid JSON","error");return}const method=item._id?"PUT":"POST";const url=item._id?`/api/admin/${resource}/${item._id}`:`/api/admin/${resource}`;api(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(d=>{toast(d.message);resourceViewAfter(resource)}).catch(e=>toast(e.message,"error"))}
function resourceViewAfter(r){resource(r)}
function deleteRecord(r,id){if(!confirm("Delete this record?"))return;api(`/api/admin/${r}/${id}`,{method:"DELETE"}).then(d=>{toast(d.message);resource(r)}).catch(e=>toast(e.message,"error"))}
function admins(){title.textContent="Admin Users";root.innerHTML=`<div class="dashboard-card full-card"><h2 class="section-title">Create Admin User</h2><form id="admin-form" class="profile-form"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><div class="span"><button class="btn primary">Create Admin</button></div></form><p class="muted">Use the seed account for first access: admin@campus.local / Admin@12345. Change it after login.</p></div>`;document.getElementById("admin-form").onsubmit=async e=>{e.preventDefault();try{const body=Object.fromEntries(new FormData(e.target));const d=await api("/api/admin/admins",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});toast(d.message);e.target.reset()}catch(e){toast(e.message,"error")}}}
async function show(s){try{if(s==="overview")overview();else if(s==="students")students();else if(s==="admins")admins();else resource(s);document.querySelectorAll(".side-link").forEach(b=>b.classList.toggle("active",b.dataset.section===s))}catch(e){toast(e.message,"error")}}
window.show=show;window.resource=resource;window.newRecord=newRecord;window.editRecord=editRecord;window.deleteRecord=deleteRecord;window.filterStudents=filterStudents;window.seedHint=seedHint;
document.querySelectorAll(".side-link").forEach(b=>b.addEventListener("click",()=>show(b.dataset.section)));document.getElementById("sidebar-toggle").addEventListener("click",()=>document.getElementById("sidebar").classList.toggle("open"));document.getElementById("logout").addEventListener("click",async()=>{await api("/api/auth/logout",{method:"POST"});location.href="/login.html"});(async()=>{try{const d=await api("/api/auth/me");if(d.user.role!=="admin")return location.href="/dashboard.html";overview()}catch{location.href="/login.html"}})();
